---
- name: Downloading Calico CRD
  shell: curl -O https://raw.githubusercontent.com/projectcalico/calico/v3.28.0/manifests/custom-resources.yaml
  args:
    chdir: /home/admin

- name: Replacing Calico Pod Network
  replace:
    path: /home/admin/custom-resources.yaml
    regexp: '192\.168\.0\.0\/16'
    replace: '10.244.0.0/24'

- name: Installing Calico CRD
  shell: kubectl create -f /home/admin/custom-resources.yaml
