---
- name: Uploading Kubelet Configuration
  copy:
    content: |
      apiVersion: kubelet.config.k8s.io/v1beta1
      kind: KubeletConfiguration
      serverTLSBootstrap: true
      cgroupDriver: systemd
    dest: /var/lib/kubelet/config.yaml
  notify: Restart Kubelet