- name: Adding AWS Load Balancer Controller Repository
  shell: |
    helm repo add eks https://aws.github.io/eks-charts
    helm repo update

- name: Installing AWS Load Balancer Controller
  shell: |
    helm install aws-load-balancer-controller eks/aws-load-balancer-controller -n kube-system \
      --set clusterName=devops-na-nuvem-cluster \
      --set hostNetwork=true


