---
- name: Terraform Outputs
  shell: terraform output -json > outputs.json
  args:
    chdir: "{{terraform_path}}/server"
  delegate_to: localhost
  environment:
    AWS_REGION: "{{aws_region}}"
    AWS_ACCESS_KEY_ID: "{{aws_access_key_id}}"
    AWS_SECRET_ACCESS_KEY: "{{aws_secret_access_key}}"