---
- name: Copy Template File
  vars:
    terraform_outputs: "{{ lookup('file', '{{terraform_path}}/server/outputs.json') }}"
    nlb_dns_name: "{{ terraform_outputs.nlb_dns_name.value }}"
  template:
    src: kubeadm-init.j2
    dest: /home/admin/kubeadm-init.yml
