---
- name: Installing ArgoCD
  shell: |
    kubectl create namespace argocd --dry-run=client -o yaml | kubectl apply -f -
    kubectl apply --server-side --force-conflicts -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

- name: Installing Argo Rollouts
  shell: |
    kubectl create namespace argo-rollouts --dry-run=client -o yaml | kubectl apply -f -
    kubectl apply -n argo-rollouts -f https://github.com/argoproj/argo-rollouts/releases/latest/download/install.yaml